import type { CatalogueDetail, CatalogueProvenanceRow, SeriesPoint } from '../types'
import { guid, sha256 } from './ids'

/** Invented indicators only. Twelve, with deliberately varied staleness. */
interface Seed {
  key: string
  name_en: string
  name_ar: string
  detail_name_en: string
  type: string
  unit_en: string
  unit_ar: string
  format: string
  polarity: 'Higher is better' | 'Lower is better' | 'Neutral'
  source: string
  definition: string
  granularity: 'Monthly' | 'Quarterly' | 'Annual'
  /** Last loaded period, as a label plus an ISO date. */
  last: [string, string]
  points: number
  start: number
  step: number
  target: number | null
  target_year: number | null
  baseline: number | null
  baseline_year: number | null
  is_main: boolean
  decimals: number
}

const SEEDS: Seed[] = [
  {
    key: 'cpi',
    name_en: 'Consumer price index',
    name_ar: 'الرقم القياسي لأسعار المستهلك',
    detail_name_en: 'General index, all groups',
    type: 'Price index',
    unit_en: 'Index (2018 = 100)',
    unit_ar: 'الرقم القياسي (2018 = 100)',
    format: '0.00',
    polarity: 'Neutral',
    source: 'Consumer price statistics bulletin',
    definition:
      'A measure of the average change over time in the prices paid by households for a fixed basket of consumer goods and services. The general index covers all twelve expenditure groups.',
    granularity: 'Monthly',
    last: ['Aug 2026', '2026-08-01'],
    points: 104,
    start: 100.4,
    step: 0.21,
    target: null,
    target_year: null,
    baseline: 100,
    baseline_year: 2018,
    is_main: true,
    decimals: 2,
  },
  {
    key: 'gdp-growth',
    name_en: 'Real GDP growth rate',
    name_ar: 'معدل نمو الناتج المحلي الإجمالي الحقيقي',
    detail_name_en: 'Year-on-year, constant prices',
    type: 'National accounts',
    unit_en: 'Percent',
    unit_ar: 'نسبة مئوية',
    format: '0.0%',
    polarity: 'Higher is better',
    source: 'Quarterly national accounts',
    definition:
      'The percentage change in gross domestic product at constant prices compared with the same quarter of the previous year.',
    granularity: 'Quarterly',
    last: ['Q2 2026', '2026-04-01'],
    points: 38,
    start: 1.8,
    step: 0.06,
    target: 4,
    target_year: 2030,
    baseline: 1.6,
    baseline_year: 2018,
    is_main: true,
    decimals: 1,
  },
  {
    key: 'unemployment',
    name_en: 'Unemployment rate',
    name_ar: 'معدل البطالة',
    detail_name_en: 'Total, population aged 15 and over',
    type: 'Labour force',
    unit_en: 'Percent',
    unit_ar: 'نسبة مئوية',
    format: '0.00%',
    polarity: 'Lower is better',
    source: 'Labour force sample survey',
    definition:
      'The number of unemployed persons as a percentage of the labour force, where the labour force is the sum of employed and unemployed persons aged 15 and over.',
    granularity: 'Quarterly',
    last: ['Q3 2024', '2024-07-01'],
    points: 29,
    start: 0.18,
    step: -0.002,
    target: 0.1,
    target_year: 2030,
    baseline: 0.14,
    baseline_year: 2018,
    is_main: true,
    decimals: 2,
  },
  {
    key: 'lfpr',
    name_en: 'Labour force participation rate',
    name_ar: 'معدل المشاركة في القوى العاملة',
    detail_name_en: 'Total, population aged 15 and over',
    type: 'Labour force',
    unit_en: 'Percent',
    unit_ar: 'نسبة مئوية',
    format: '0.0%',
    polarity: 'Higher is better',
    source: 'Labour force sample survey',
    definition:
      'The labour force as a percentage of the working-age population aged 15 and over.',
    granularity: 'Annual',
    last: ['2025', '2025-01-01'],
    points: 11,
    start: 86.1,
    step: 0.24,
    target: 90,
    target_year: 2030,
    baseline: 86.4,
    baseline_year: 2018,
    is_main: true,
    decimals: 1,
  },
  {
    key: 'non-hydrocarbon',
    name_en: 'Non-hydrocarbon share of GDP',
    name_ar: 'نسبة الأنشطة غير النفطية من الناتج المحلي الإجمالي',
    detail_name_en: 'Current prices, share of total',
    type: 'National accounts',
    unit_en: 'Percent',
    unit_ar: 'نسبة مئوية',
    format: '0.0%',
    polarity: 'Higher is better',
    source: 'Annual national accounts bulletin',
    definition:
      'The share of gross domestic product at current prices generated by activities other than mining and quarrying of hydrocarbons.',
    granularity: 'Annual',
    last: ['2024', '2024-01-01'],
    points: 9,
    start: 58.2,
    step: 0.7,
    target: 70,
    target_year: 2030,
    baseline: 58.9,
    baseline_year: 2018,
    is_main: false,
    decimals: 1,
  },
  {
    key: 'population',
    name_en: 'Total population',
    name_ar: 'إجمالي عدد السكان',
    detail_name_en: 'Mid-year estimate, both sexes',
    type: 'Demography',
    unit_en: 'Persons',
    unit_ar: 'أشخاص',
    format: '#,##0',
    polarity: 'Neutral',
    source: 'Population estimates',
    definition:
      'The estimated resident population at mid-year, covering citizens and non-citizens present in the country.',
    granularity: 'Annual',
    last: ['2026', '2026-01-01'],
    points: 12,
    start: 2740000,
    step: 31000,
    target: null,
    target_year: null,
    baseline: 2760000,
    baseline_year: 2018,
    is_main: true,
    decimals: 0,
  },
  {
    key: 'exports',
    name_en: 'Total exports of goods',
    name_ar: 'إجمالي صادرات السلع',
    detail_name_en: 'Free on board, all commodities',
    type: 'Foreign trade',
    unit_en: 'Million QAR',
    unit_ar: 'مليون ريال قطري',
    format: '#,##0',
    polarity: 'Higher is better',
    source: 'Foreign merchandise trade statistics',
    definition:
      'The total value of goods leaving the country, valued free on board at the customs frontier.',
    granularity: 'Monthly',
    last: ['Jul 2026', '2026-07-01'],
    points: 96,
    start: 24800,
    step: 96,
    target: null,
    target_year: null,
    baseline: 25400,
    baseline_year: 2018,
    is_main: true,
    decimals: 0,
  },
  {
    key: 'imports',
    name_en: 'Total imports of goods',
    name_ar: 'إجمالي واردات السلع',
    detail_name_en: 'Cost, insurance and freight, all commodities',
    type: 'Foreign trade',
    unit_en: 'Million QAR',
    unit_ar: 'مليون ريال قطري',
    format: '#,##0',
    polarity: 'Neutral',
    source: 'Foreign merchandise trade statistics',
    definition:
      'The total value of goods entering the country, valued including cost, insurance and freight.',
    granularity: 'Monthly',
    last: ['Jul 2026', '2026-07-01'],
    points: 96,
    start: 9900,
    step: 41,
    target: null,
    target_year: null,
    baseline: 10200,
    baseline_year: 2018,
    is_main: true,
    decimals: 0,
  },
  {
    key: 'life-expectancy',
    name_en: 'Life expectancy at birth',
    name_ar: 'متوسط العمر المتوقع عند الميلاد',
    detail_name_en: 'Both sexes combined',
    type: 'Health',
    unit_en: 'Years',
    unit_ar: 'سنوات',
    format: '0.0',
    polarity: 'Higher is better',
    source: 'Vital statistics annual bulletin',
    definition:
      'The average number of years a newborn would live if subject throughout life to the mortality rates observed in the reference year.',
    granularity: 'Annual',
    last: ['2022', '2022-01-01'],
    points: 8,
    start: 79.4,
    step: 0.16,
    target: 82,
    target_year: 2030,
    baseline: 79.9,
    baseline_year: 2018,
    is_main: true,
    decimals: 1,
  },
  {
    key: 'literacy',
    name_en: 'Adult literacy rate',
    name_ar: 'معدل معرفة القراءة والكتابة للبالغين',
    detail_name_en: 'Population aged 15 and over',
    type: 'Education',
    unit_en: 'Percent',
    unit_ar: 'نسبة مئوية',
    format: '0.0%',
    polarity: 'Higher is better',
    source: 'Education statistics bulletin',
    definition:
      'The percentage of the population aged 15 and over able to read and write a short simple statement about everyday life.',
    granularity: 'Annual',
    last: ['2021', '2021-01-01'],
    points: 7,
    start: 96.6,
    step: 0.19,
    target: 99,
    target_year: 2030,
    baseline: 97.2,
    baseline_year: 2018,
    is_main: true,
    decimals: 1,
  },
  {
    key: 'renewables',
    name_en: 'Renewable share of electricity generation',
    name_ar: 'نسبة الطاقة المتجددة من توليد الكهرباء',
    detail_name_en: 'Grid-connected generation',
    type: 'Energy',
    unit_en: 'Percent',
    unit_ar: 'نسبة مئوية',
    format: '0.00%',
    polarity: 'Higher is better',
    source: 'Energy and water statistics',
    definition:
      'Electricity generated from renewable sources as a percentage of total grid-connected generation.',
    granularity: 'Annual',
    last: ['2024', '2024-01-01'],
    points: 7,
    start: 0.4,
    step: 0.42,
    target: 20,
    target_year: 2030,
    baseline: 0.3,
    baseline_year: 2018,
    is_main: false,
    decimals: 2,
  },
  {
    key: 'hotel-occupancy',
    name_en: 'Hotel occupancy rate',
    name_ar: 'معدل إشغال الفنادق',
    detail_name_en: 'All classifications',
    type: 'Tourism',
    unit_en: 'Percent',
    unit_ar: 'نسبة مئوية',
    format: '0.0%',
    polarity: 'Higher is better',
    source: 'Tourism performance report',
    definition:
      'Occupied room nights as a percentage of available room nights across all classified establishments.',
    granularity: 'Monthly',
    last: ['Jul 2026', '2026-07-01'],
    points: 84,
    start: 61.2,
    step: 0.13,
    target: 75,
    target_year: 2030,
    baseline: 62.1,
    baseline_year: 2018,
    is_main: true,
    decimals: 1,
  },
]

function shiftPeriod(iso: string, granularity: Seed['granularity'], back: number): string {
  const date = new Date(`${iso}T00:00:00Z`)
  const months = granularity === 'Monthly' ? 1 : granularity === 'Quarterly' ? 3 : 12
  date.setUTCMonth(date.getUTCMonth() - back * months)
  return date.toISOString().slice(0, 10)
}

const MONTHS = [
  'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
]

function label(iso: string, granularity: Seed['granularity']): string {
  const date = new Date(`${iso}T00:00:00Z`)
  const year = date.getUTCFullYear()
  if (granularity === 'Annual') return String(year)
  if (granularity === 'Quarterly') return `Q${Math.floor(date.getUTCMonth() / 3) + 1} ${year}`
  return `${MONTHS[date.getUTCMonth()]} ${year}`
}

function round(value: number, decimals: number): number {
  const factor = 10 ** decimals
  return Math.round(value * factor) / factor
}

function buildSeries(seed: Seed): SeriesPoint[] {
  const points: SeriesPoint[] = []
  // Keep the plotted window readable; the full point count still reports as data_points.
  const shown = Math.min(seed.points, seed.granularity === 'Monthly' ? 24 : 12)
  for (let i = shown - 1; i >= 0; i--) {
    const iso = shiftPeriod(seed.last[1], seed.granularity, i)
    const step = seed.points - 1 - i
    const wobble = Math.sin(step * 1.7) * seed.step * 1.6
    const actual = round(seed.start + seed.step * step + wobble, seed.decimals)
    const target =
      seed.target === null
        ? null
        : round(seed.start + (seed.target - seed.start) * ((step + 1) / (seed.points + 6)), seed.decimals)
    points.push({
      record_id: guid(`${seed.key}-point-${i}`),
      period_label: label(iso, seed.granularity),
      period_date: iso,
      granularity: seed.granularity,
      country_en: 'Qatar',
      actual,
      target,
      // Outlook only on the most recent point, and not for every indicator.
      outlook: i === 0 && seed.target !== null ? round(actual + seed.step * 2, seed.decimals) : null,
    })
  }
  return points
}

function buildProvenance(): CatalogueProvenanceRow[] {
  return [
    {
      table_name: 'published_data_points',
      source_file: 'published_data_points_2026_09_01.xlsx',
      file_sha256: sha256('published_data_points_2026_09_01'),
      rows_in_file: 18420,
      rows_in_table: 17944,
      loaded_at: '2026-09-01T02:14:38Z',
    },
    {
      table_name: 'indicator_details',
      source_file: 'indicator_details_export_2026_09_01.xlsx',
      file_sha256: sha256('indicator_details_export_2026_09_01'),
      rows_in_file: 612,
      rows_in_table: 588,
      loaded_at: '2026-09-01T02:12:09Z',
    },
    {
      table_name: 'indicators',
      source_file: 'indicator_export_2026_09_01.xlsx',
      file_sha256: sha256('indicator_export_2026_09_01'),
      rows_in_file: 531,
      rows_in_table: 470,
      loaded_at: '2026-09-01T02:11:02Z',
    },
  ]
}

export const CATALOGUE: CatalogueDetail[] = SEEDS.map((seed) => {
  const series = buildSeries(seed)
  const first = series[0]
  return {
    indicator_id: guid(`${seed.key}-indicator`),
    indicator_detail_id: guid(`${seed.key}-detail`),
    published_detail_id: guid(`${seed.key}-published`),
    name_en: seed.name_en,
    name_ar: seed.name_ar,
    detail_name_en: seed.detail_name_en,
    indicator_type_en: seed.type,
    unit_en: seed.unit_en,
    unit_ar: seed.unit_ar,
    format: seed.format,
    polarity_en: seed.polarity,
    target_value: seed.target,
    target_year: seed.target_year,
    baseline_value: seed.baseline,
    baseline_year: seed.baseline_year,
    data_source_en: seed.source,
    definition_en: seed.definition,
    data_points: seed.points,
    first_period: first?.period_label ?? null,
    last_period: seed.last[0],
    is_main: seed.is_main,
    series,
    provenance: buildProvenance(),
  }
})

export const CATALOGUE_BY_KEY = new Map(SEEDS.map((seed, i) => [seed.key, CATALOGUE[i]]))

/** The catalogue detail endpoint accepts any of the three ids. */
export function findIndicator(id: string): CatalogueDetail | undefined {
  return CATALOGUE.find(
    (row) =>
      row.indicator_id === id ||
      row.indicator_detail_id === id ||
      row.published_detail_id === id,
  )
}
